name: deepfake_detection
description: Deepfake Detection Flutter App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  supabase_flutter: ^2.5.4
  share_plus: ^7.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true